### ISSUE TITLE
what are the advantages convo?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [anudit/convo#2]
Also, why to be so dependent of a blockchain controlled by coporation banks like ethereum?
why not to let developers to create their own blockchain?

**Comment by anudit** [comment]
Hey @ROBERT-MCDOWELL, 

Convo enables developers add a Social Layer to any platform and get all the benefits of Web3, like Composability, Data Sovereignty & Ownership out of the box, without having to worry about any of the complexities associated with it. 

Convo uses the `personal_sign` method of a Web3 Wallet to prove ownership of an address. This means Convo can function on any EVM compatible chain, as long as the wallet supports the spec (Almost all do), even Polkadot or Substrate based custom blockchains. 

Happy to have you in the community https://discord.com/invite/MFtmrng9J7

**Comment by ROBERT-MCDOWELL** [comment]
@anudit, do you know any script in whatever language helping me to create my own blockchain genesis conformed to the EVM?
couldn't find it.

**Comment by anudit** [comment]
Yeah @ROBERT-MCDOWELL, Checkout https://substrate.dev/en/

**Comment by ROBERT-MCDOWELL** [comment]
thx much!
